on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Embedded Builds

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - features: ""
            target: thumbv7em-none-eabihf
          - feature: portable-atomic/critical-section
            target: thumbv6m-none-eabi

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv6m-none-eabi, thumbv7em-none-eabihf

      - run: cargo build --manifest-path core/Cargo.toml --no-default-features --features=${{ matrix.feature }} --target=${{ matrix.target }}
